name: riverhotel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  logger: ^1.1.0
  basic_utils: ^3.4.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.0
  global_configs: ^1.1.1
  flutter_easyloading: ^3.0.3
  auto_route: ^3.0.4
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  curved_navigation_bar: ^1.0.1
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.1.0+1
  pin_code_fields: ^7.3.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_switch: ^0.3.2
  webview_flutter: ^2.3.1
  percent_indicator: ^3.4.0
  url_launcher: ^6.0.15
  pull_to_refresh: ^2.0.0
  graphql: ^5.0.0
  animate_do: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  image_picker: ^0.8.1+3
  connectivity: ^3.0.6
  dropdown_button2: ^1.4.0
  flutter_credit_card_new: ^0.0.4
  flutter_keyboard_visibility: ^5.1.1
  #TODO: need update flutter 3.0.0
  firebase_auth: ^3.3.17
  firebase_core: ^1.3.0
  firebase_storage: ^10.2.15
  timer_count_down: ^2.2.1
  local_auth: ^2.0.0
  table_calendar: ^3.0.5
  google_maps_flutter: ^2.1.8
  geolocator: ^8.2.1
  photo_view: ^0.13.0
  modal_bottom_sheet: ^2.0.1
  dotted_border: ^2.0.0+2
  uuid: ^3.0.6
  qr_flutter: ^4.0.0
  pattern_formatter: ^2.0.0
  share_plus: ^4.0.5
  tutorial_coach_mark: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/translations/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600  