export 'splash/splash.dart';
export 'intro/intro.dart';
export 'chat/chat.dart';
export 'main/main.dart';
export 'home/home.dart';
export 'profile/profile.dart';
export 'doctor/doctor.dart';
export 'choose/choose.dart';
export 'appointment/appointment.dart';
